import { Link, useLocation } from "@tanstack/react-router";
import { Activity, BarChart3, ChevronDown, Database, FileClock, LayoutDashboard, Menu, PanelLeftClose, Settings, ShieldCheck, Sparkles, Table2, Upload, Users, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { dataSources } from "@/mocks/fixtures";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const navigation = [
  { label: "Dashboard", to: "/dashboard", icon: LayoutDashboard }, { label: "AI SQL Agent", to: "/agent", icon: Sparkles }, { label: "Data Sources", to: "/data-sources", icon: Database }, { label: "Schema Explorer", to: "/schema-explorer", icon: Table2 }, { label: "History", to: "/history", icon: FileClock }, { label: "Saved Queries", to: "/saved-queries", icon: BarChart3 }, { label: "Admin", to: "/admin", icon: Users },
] as const;

export function SecureShell({ children }: { children: ReactNode }) {
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const location = useLocation();
  return <div className="app-canvas min-h-screen text-foreground"><div className="relative mx-auto flex max-w-[1600px] gap-5 p-4 sm:p-5">
    <aside className={cn("glass-panel sticky top-5 z-30 hidden h-[calc(100vh-2.5rem)] shrink-0 flex-col rounded-2xl p-3 md:flex", collapsed ? "w-[72px]" : "w-60")}>
      <div className={cn("flex items-center gap-2.5 px-2 py-2", collapsed && "justify-center px-0")}><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-ink font-mono text-sm font-semibold text-primary-foreground">S</div>{!collapsed && <div><p className="text-sm font-semibold leading-none">SecureSQL</p><p className="mt-1 text-[11px] text-slate2">RAG data analyst</p></div>}</div>
      <nav className="mt-4 flex flex-col gap-0.5 text-sm">{navigation.map(({ label, to, icon: Icon }) => <Link key={to} to={to} onClick={() => setMobileOpen(false)} className={cn("focus-ring flex items-center gap-2.5 rounded-lg px-3 py-2 font-medium text-slate2 transition-colors hover:bg-card/60 hover:text-foreground", location.pathname === to && "bg-card/80 font-semibold text-foreground shadow-sm ring-1 ring-card", collapsed && "justify-center px-2")} title={collapsed ? label : undefined}><Icon className={cn("size-4", location.pathname === to && "text-brand")} />{!collapsed && label}</Link>)}</nav>
      {!collapsed && <div className="mt-auto rounded-xl border border-card/70 bg-card/50 p-3"><p className="eyebrow">Vector index</p><div className="mt-2 flex items-center gap-2 text-xs font-medium"><span className="pulse-dot size-2 rounded-full bg-low" />4 sources synced</div><div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-ink/10"><div className="h-full w-[86%] rounded-full bg-brand" /></div><p className="mt-1.5 font-mono text-[10px] text-slate2">86% · updated 12m ago</p></div>}
      <Button variant="ghost" size="icon" aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"} className="mt-3 self-end text-slate2" onClick={() => setCollapsed((v) => !v)}>{collapsed ? <PanelLeftClose className="rotate-180" /> : <PanelLeftClose />}</Button>
    </aside>
    {mobileOpen && <div className="fixed inset-0 z-40 bg-ink/20 md:hidden" onClick={() => setMobileOpen(false)}><aside className="glass-panel h-full w-72 p-4" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><span className="font-semibold">SecureSQL</span><Button variant="ghost" size="icon" aria-label="Close menu" onClick={() => setMobileOpen(false)}><X /></Button></div><nav className="mt-5 flex flex-col gap-1">{navigation.map(({ label, to, icon: Icon }) => <Link key={to} to={to} onClick={() => setMobileOpen(false)} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate2 hover:bg-card/60"><Icon className="size-4" />{label}</Link>)}</nav></aside></div>}
    <div className="min-w-0 flex-1"><header className="glass-panel sticky top-4 z-20 mb-4 flex min-h-14 flex-wrap items-center gap-2 rounded-2xl px-3 py-2.5 sm:top-5 sm:px-4"><Button variant="ghost" size="icon" className="md:hidden" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu /></Button><button className="focus-ring flex min-w-0 items-center gap-2 rounded-lg border border-card/70 bg-card/70 px-3 py-1.5 text-sm font-medium"><span className="pulse-dot size-2 shrink-0 rounded-full bg-low" /><span className="hidden sm:inline">Postgres</span><span className="truncate">{dataSources[0]?.name ?? "northwind-prod"}</span><ChevronDown className="size-3.5 shrink-0 text-slate2" /></button><span className="hidden rounded-md bg-ink/5 px-2 py-1 font-mono text-[11px] text-slate2 sm:inline">env: production · read-only</span><div className="ml-auto flex items-center gap-2 sm:gap-3"><span className="hidden text-xs text-slate2 lg:inline">⌘K to query</span><div className="grid size-8 place-items-center rounded-full bg-brand/10 text-xs font-semibold text-brand">MK</div></div></header>{children}</div>
  </div></div>;
}

export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h1><p className="mt-1 max-w-2xl text-sm text-slate2">{description}</p></div>{action}</div>; }